### ISSUE TITLE
unable to catch SystemRegisterError exception

### ISSUE THREAD

**Issue by xun-xh** [timeyyy/system_hotkey#30]
**code:**

`from system_hotkey import *

def some_func(event, hotkey, args):
	print(event, hotkey, args)

try:
	hk = SystemHotkey(consumer=some_func)
	hk.register(('control', 'u'))
	hk_1 = SystemHotkey(consumer=some_func)
	hk_1.register(('control', 'u'), overwrite=True)
	print(456)
except Exception as e:
	print(123)

while True:
	pass
`

**result:**

`test.py 
456
Exception ignored in thread started by: <bound method SystemHotkey._nt_wait of <system_hotkey.system_hotkey.SystemHotkey object at 0x000002052BA864F0>>
Traceback (most recent call last):
  File "D:\Xiv-Tool\venv\lib\site-packages\system_hotkey\system_hotkey.py", line 692, in _nt_wait
    remove_or_add()
  File "D:\Xiv-Tool\venv\lib\site-packages\system_hotkey\system_hotkey.py", line 304, in <lambda>
    self.hk_action_queue.put(lambda:nt_register())
  File "D:\Xiv-Tool\venv\lib\site-packages\system_hotkey\system_hotkey.py", line 303, in nt_register
    self._the_grab(keycode, masks, uniq)
  File "D:\Xiv-Tool\venv\lib\site-packages\system_hotkey\system_hotkey.py", line 724, in _nt_the_grab
    raise SystemRegisterError(msg)
system_hotkey.system_hotkey.SystemRegisterError: The bind could be in use elsewhere: u
`

**Expected to print 123, but not**

**Comment by Imandyr** [comment]
I have the same problem. Any ideas how to catch it?

**Comment by amadeok** [comment]
Hello, monkey patch it

```

        def make_checked_hotkey(*args, **kwargs):
            hk = SystemHotkey(*args, **kwargs)
            orig_grab = hk._nt_the_grab

            hk._reg_lock = threading.Lock()
            hk._reg_result = {"event": None, "error": None}

            def patched_grab(keycode, masks, id, root=None):
                try:
                    orig_grab(keycode, masks, id, root)
                except SystemRegisterError as e:
                    if hk._reg_result["event"] is not None:
                        hk._reg_result["error"] = e
                    raise
                finally:
                    if hk._reg_result["event"] is not None:
                        hk._reg_result["event"].set()

            hk._the_grab = patched_grab
            return hk



        def register_and_check(hk, hotkey, callback, overwrite=False, timeout=2.0):
            with hk._reg_lock:
                event = threading.Event()
                hk._reg_result["event"] = event
                hk._reg_result["error"] = None

                hk.register(hotkey, callback=callback, overwrite=overwrite)

                if not event.wait(timeout):
                    raise TimeoutError("Registration timed out")
                if hk._reg_result["error"] is not None:
                    raise hk._reg_result["error"]
                return True

        hk = make_checked_hotkey() 
register_and_check(hk, ("alt", "tab"), lambda e: print("Alt+Tab"))

```
