### ISSUE TITLE
python-xlib

### ISSUE THREAD

**Issue by Xcelled** [timeyyy/system_hotkey#6]
The readme says `For x11 you will can either use xcffib (bsd license), or you may use the python xlib bindings (gpl license)` but if you attempt to import system_hotkey without xcffib, you get an error:

```
>>> from system_hotkey import SystemHotkey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/__init__.py", line 1, in <module>
    from system_hotkey.system_hotkey import *
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/system_hotkey.py", line 142, in <module>
    from . import xpybutil_keybind as keybind
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/xpybutil_keybind.py", line 14, in <module>
    import xcffib.xproto as xproto
ImportError: No module named 'xcffib'
```

Is xcffib always required?

**Comment by timeyyy** [comment]
Oops, will take a look today.

**Comment by Xcelled** [comment]
As a note, I'm on Linux Mint 18.

**Comment by timeyyy** [comment]
I have recommended that xlib no longer be used, i have no time frame for fixing this. 

Xlib support is also broken, binding to `escape` for instance will fail. This could be solved be changing `_xlib_get_keycode` implementation  to the same as `_xcb_get_keycode`.

To fix xlib and remove the xcb dependancy is a matter of implementing `_xlib_get_keysym` and `_xlib_get_keycode` properly.  xpybutil_keyind.py is a good reference, the issue is described with a solution in lisp [here](https://lists.gnu.org/archive/html/stumpwm-devel/2006-04/msg00033.html).

**Comment by Xcelled** [comment]
Xlib itself can do this, unless I'm misunderstanding what's required. I wrote this segment for another project.

```
from Xlib import X, XK
	def toNativeKeycode(self, key):
		''' Returns the X11 native keycode for a QT Key '''

		keysym = XK.string_to_keysym(QKeySequence(key).toString())
		if keysym == X.NoSymbol:
			keysym = int(key)
		#endif

		return self.display.keysym_to_keycode(keysim)
	#enddef
```

 It uses QT, but only to get a string representation of a QT key. In other words, you should be able to call string_to_keysym with a normal string, tho the int() call would need to be replaced with ord().
