### ISSUE TITLE
SystemRegisterError not raised on caller's thread

### ISSUE THREAD

**Issue by Xcelled** [timeyyy/system_hotkey#7]
If you try to bind to a hotkey that's in use by another program, system hotkey raises a RegisterException, but in a new thread, so it's not caught by any handlers you may have installed.

Sample, assumes you have another program bound to alt-shift-1:
```
from system_hotkey import SystemHotkey, SystemRegisterError

hk = SystemHotkey()

try: hk.register(('shift', 'alt', '1'), callback=lambda e: print('hi'))
except SystemRegisterError: print('Caught error')

input() # Hold program open until you press enter
````

Results:
```
$ python3 test.py
Unhandled exception in thread started by <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7f46508a37f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/system_hotkey.py", line 790, in _xcb_the_grab
    xproto.GrabMode.Async, xproto.GrabMode.Async).check()
  File "/usr/local/lib/python3.5/dist-packages/xcffib/__init__.py", line 330, in check
    self.conn.request_check(self.sequence)
  File "/usr/local/lib/python3.5/dist-packages/xcffib/__init__.py", line 557, in wrapper
    return f(*args)
  File "/usr/local/lib/python3.5/dist-packages/xcffib/__init__.py", line 663, in request_check
    self._process_error(err)
  File "/usr/local/lib/python3.5/dist-packages/xcffib/__init__.py", line 634, in _process_error
    raise error(buf)
xcffib.xproto.AccessError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/util.py", line 37, in call_functions
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/system_hotkey.py", line 341, in register
    self._the_grab(keycode, masks)
  File "/usr/local/lib/python3.5/dist-packages/system_hotkey/system_hotkey.py", line 797, in _xcb_the_grab
    raise SystemRegisterError(msg)
system_hotkey.system_hotkey.SystemRegisterError: The bind could be in use elsewhere: 1
```

**Comment by timeyyy** [comment]
@Xcelled The last commit should have fixed the issue, i added some tests for it as well, are you able to test it on windows?

**Comment by Xcelled** [comment]
@timeyyy yes, at some point I can fire up my Windows machine. May not be for a day or two, though.
